#!/usr/bin/env bash
# Displays listening TCP and UDP ports with PID and program name using lsof

# TCP listening sockets
echo "Active TCP connections (only servers)"
sudo lsof -iTCP -sTCP:LISTEN -Pn -n

# UDP listening sockets
echo -e "\nActive UDP connections (only servers)"
sudo lsof -iUDP -Pn -n
