#!/usr/bin/env bash
# Displays all active IPv4 IP addresses on the machine including localhost

# Print localhost first
echo "127.0.0.1"

# Print other IPv4 addresses
hostname -I | tr ' ' '\n' | grep -v '^127\.0\.0\.1$'
